apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground-deployment
  labels:
    name: wil-playground
spec:
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
        - name: wil-playground
          image: wil42/playground:v2
          ports:
            - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wil-playground
  name: wil-playground
spec:
  ports:
    - nodePort: 30080
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: wil-playground
  type: NodePort